image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-order.jar -port=7777


build_script:
  - chmod +x gradlew
  - chmod +x ./driver/linux/chromedriver
  - ./gradlew test --info