image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - chmod +x gradlew
  - chmod 755 ./driver/linux/chromedriver
  - ./gradlew test --info